export let muro = [{
    mensaje: 'NJ NBESF FTUB NVZ NPMFTUB DPONJHP. OP MMBNFT B DBTB. OPT WFNPT NBOBOB.',
    offset: 1
  },
  {
    mensaje: 'BR HVFXFKH D WX FUXVK KDEODQGR D VX DPLJD. HOODV YDQ DO FLQH HVWD QRFKH SDUD YHU HVD QXHYD SHOLFXOD FXUVL. GHEHULD LUWH B OODPDU VX DWHQFLRQ.',
    offset: 3
  }
  ]
